### ISSUE TITLE
Ability to use custom configurations.

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/css-property-sorter#1]
As suggested by @mrmlnc add the ability to use a self-written JSON file for the sort order.

**Comment by lysyi3m** [comment]
+1! It could be more useful to have ability to provide custom config.

**Comment by mrmlnc** [comment]
Yeap! :+1:

**Comment by Siilwyn** [comment]
I'm currently working on this enhancement, some refactoring is needed for this to work.

:calendar: ETA 3 - 7 days.
