### ISSUE TITLE
Mention capabilities in the readme

### ISSUE THREAD

**Issue by ai** [Siilwyn/css-property-sorter#3]
PostCSS can work with SCSS too by [postcss-scss](https://github.com/postcss/postcss-scss) syntax.

You should mention it in docs.

**Comment by Siilwyn** [comment]
Seems like a good idea, I think the readme is missing a 'why to use?' section that states the capabilities of this module. Once issue #1 is solved I think the following points can be added:
- Lightweight module that does one thing well.
- Easily combined with other PostCSS plugins.
- Sass support using [postcss-scss](https://github.com/postcss/postcss-scss/).
- Up-to-date CSS properties, scraped from [DevDocs](https://devdocs.io/).
- Supports multiple sorting orders as well as a custom defined order.
