### ISSUE TITLE
Revamp CSScomb order to Zen Coding

### ISSUE THREAD

**Issue by pepelsbey** [Siilwyn/css-property-sorter#4]
There’s a sorting order used in Yandex projects (since 2008 or even earlier) and there should be a documentation for that somewhere, I’m a right @vithar? It would be good to have that option available so this plugin could be used by Yandex developers and BEM fans.

Sorting order that you call “CSScomb” has been invented by myself and @flackus around 2006 and [used and documented](https://code.google.com/p/zen-coding/wiki/ZenCSSPropertiesEn) in Zen Coding project later in 2008. I could provide updated documentation including new properties if you’d like.

This issue could be merged into #2, but at least I’d like you to not remove Zed Coding sorting as I’m willing to develop it further and this plugin is a good chance to do so.

**Comment by Siilwyn** [comment]
@pepelsbey thanks for your suggestion. I've added Yandex sorting as a possibility to issue #2.

If you could update the documentation for Zen Coding I would be more than willing to rename and update the 'CSScomb' order. If you have the time and could propose a JSON file that follows the Zen Coding order that would be awesome!

**Comment by pepelsbey** [comment]
Will do! In the beginning of the next week.

**Comment by Siilwyn** [comment]
Nice! You can save yourself some hassle by using the [csscomb.json](https://github.com/Siilwyn/css-property-sorter/blob/master/orders/csscomb.json) file as a starting point. Let me know if you run into any trouble or doubts I'll be happy to assist. :smiley:

**Comment by vithar** [comment]
@pepelsbey http://vitaly.harisov.name/article/css-fast-typing.html (in Russian)

**Comment by Siilwyn** [comment]
Hi there @pepelsbey I have no idea if you are working on the order but I've decided to move the project forward by only including well documented sorting orders that are reviewed by their author to be included by default and giving the tool a better name.

Hence I'm closing this issue.

**Comment by pepelsbey** [comment]
@Siilwyn, sorry for keeping you waiting, still haven’t found time to do this.

**Comment by Siilwyn** [comment]
@pepelsbey, no problem at all. If you still want to create it the order has to be publicly documented in English for example like [SMACSS](https://smacss.com/book/formatting#grouping).
